---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>
  joyent_username: <%= ENV['SDC_CLI_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_CLI_IDENTITY'] %>
  joyent_keyname: <%= ENV['SDC_CLI_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_CLI_URL'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:
- name: debian-7.2
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20140318
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 3101045
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-14.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 3240036
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: centos-5.8
  driver_plugin: digitalocean
  driver_config:
    image_id: 1601
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

# selinux-permissive
- name: centos-6.4
  driver_plugin: digitalocean
  driver_config:
    image_id: 3797680
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[selinux]
  attributes:
    selinux:
      state: disabled

- name: fedora-20
  driver_plugin: digitalocean
  driver_config:
    image_id: 3243145
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>

- name: amazon-2014.03
  driver_plugin: ec2
  driver_config:
    image_id: ami-6b726502
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

# - name: smartos-13.4.0
#   driver_plugin: joyent
#   driver_config:
#     joyent_image_id: ff86eb8a-a069-11e3-ae0e-4f3c8983a91c
#     joyent_flavor_id: g3-standard-4-smartos
#     username: root
#     ssh_key: <%= ENV['SDC_CLI_IDENTITY'] %>
#   busser:
#     ruby_bindir: '/opt/local/bin/'
#   provisioner:
#     name: chef_zero
#     sudo: false
#     chef_omnibus_url: https://raw.github.com/test-kitchen/kitchen-joyent/master/scripts/install-smartos.sh

- name: omnios-151006
  driver_plugin: ec2
  driver_config:
    availability_zone: us-east-1d
    image_id: ami-35eb835c
    flavor_id: m3.medium
    username: root
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  provisioner:
    name: chef_zero
  run_list:
  - recipe[ips-omniti]

suites:
  #
  # service22-single
  #
  - name: service22-single
    run_list:
    - recipe[httpd_service::single]
    includes: [
      'amazon-2014.03',
      'debian-7.2',
      'omnios-151006',
      'centos-5.8',
      'centos-6.4',
      'smartos-13.4.0',
      'ubuntu-12.04',
      'ubuntu-13.10',
    ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service22-multi
  #
  - name: service22-multi
    run_list:
    - recipe[httpd_service::multi]
    includes: [
      'amazon-2014.03',
      'debian-7.2',
      'omnios-151006',
      'centos-5.8',
      'centos-6.4',
      'smartos-13.4.0',
      'ubuntu-12.04',
    ]
    attributes:
      httpd:
        contact: 'bob@computers.biz'
        version: '2.2'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'

  #
  # service24-single
  #
  - name: service24-single
    run_list:
    - recipe[httpd_service::single]
    includes: [
      'amazon-2014.03',
      'fedora-20',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service24-multi
  #
  - name: service24-multi
    run_list:
    - recipe[httpd_service::multi]
    includes: [
      'amazon-2014.03',
      'fedora-20',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]
    attributes:
      httpd:
        version: '2.4'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        contact: 'alice@computers.biz'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'

  #
  # modules
  #
  - name: module-alias_22
    run_list:
    - recipe[httpd_module::alias_22]
    includes: [
      'amazon-2014.03',
      'debian-7.2',
      'omnios-151006',
      'centos-5.8',
      'centos-6.4',
      'smartos-13.4.0',
      'ubuntu-12.04'
    ]

  - name: module-alias_24
    run_list:
    - recipe[httpd_module::alias_24]
    includes: [
      'amazon-2014.03',
      'fedora-20',
      'smartos-13.4.0',
      'ubuntu-14.04',
    ]