driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  #
  # config
  #
  - name: config
    run_list:
    - recipe[httpd_config_test]

  #
  # modules
  #
  - name: module22
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-6',
      'debian-7'
      ]
    attributes:
      httpd:
        version: '2.2'

  - name: module24
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-7',
      'debian-8',
      'fedora-25',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'freebsd-10',
      'freebsd-11',
      'opensuse-leap-42'
      ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service22-single
  #
  - name: service22-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-6',
      'debian-7'
      ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service22-multi
  #
  - name: service22-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-6',
      'debian-7'
      ]
    attributes:
      httpd:
        contact: 'bob@computers.biz'
        version: '2.2'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        maxspareservers: '40'
        log_level: 'warn'
        maxkeepaliverequests: '2001'

  #
  # service22-actions
  #
  - name: service22-actions
    run_list:
    - recipe[httpd_service_test::actions]
    includes: [
      'centos-6',
      'debian-7'
      ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service24-single
  #
  - name: service24-single
    driver:
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-7',
      'fedora-25',
      'debian-8',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'freebsd-10',
      'freebsd-11',
      'opensuse-leap-42'
      ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service24-multi-docker
  #
  - name: service24-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-7',
      'debian-8',
      'fedora-25',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'freebsd-10',
      'freebsd-11',
      'opensuse-leap-42'
      ]
    attributes:
      httpd:
        version: '2.4'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        log_level: 'warn'
        run_user: 'bob'
        run_group: 'bob'
        contact: 'alice@computers.biz'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        maxspareservers: '40'
        maxkeepaliverequests: '2001'
  #
  # service24-actions
  #
  - name: service24-actions
    driver:
    run_list:
    - recipe[httpd_service_test::actions]
    includes: [
      'centos-7',
      'debian-8',
      'fedora-25',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'freebsd-10',
      'freebsd-11',
      'opensuse-leap-42'
      ]
    attributes:
      httpd:
        version: '2.4'
