---
driver:
  name: dokken
  chef_version: 12.5.1
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false
#  name: inspec

platforms:
# someara/chef container does not support centos-5 yet.
# - name: centos-5
#   driver:
#     image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-21
  driver:
    image: fedora:21
    intermediate_instructions:
    - RUN yum clean all
    pid_one_command: /usr/lib/systemd/systemd

- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

# - name: debian-8
#   driver:
#     image: debian:8
#     pid_one_command: /bin/systemd
#   run_list:
#   - recipe[apt]

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[apt]

# - name: ubuntu-15.04
#   driver:
#     image: ubuntu:15.04
#     pid_one_command: /bin/systemd
#   run_list:
#   - recipe[apt]

suites:
  #
  # config
  #
  - name: config
    run_list:
    - recipe[httpd_config_test]

  #
  # modules
  #
  - name: module22
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-5',
      'centos-6',
      'debian-7',
      'ubuntu-10.04',
      'ubuntu-12.04'
    ]
    attributes:
      httpd:
        version: '2.2'

  - name: module24
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-7',
      'fedora-21',
      'ubuntu-14.04',
      'ubuntu-15.04',
    ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service22-single
  #
  - name: service22-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-5',
      'centos-6',
      'debian-7',
      'ubuntu-12.04',
    ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service22-multi
  #
  - name: service22-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-5',
      'centos-6',
      'debian-7',
      'ubuntu-12.04',
    ]
    attributes:
      httpd:
        contact: 'bob@computers.biz'
        version: '2.2'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'

  #
  # service24-single
  #
  - name: service24-single
    driver:
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-7',
      'fedora-21',
      'debian-8',
      'ubuntu-14.04',
      'ubuntu-15.04',
    ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service24-multi-docker
  #
  - name: service24-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-7',
      'fedora-21',
      'ubuntu-14.04',
      'ubuntu-15.04'
    ]
    attributes:
      httpd:
        version: '2.4'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        contact: 'alice@computers.biz'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        minspareservers: '40'
