name 'httpd'
version '0.2.10'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'Apache 2.0'
description 'Provides httpd_service, httpd_config, and httpd_module resources'
source_url 'https://github.com/chef-cookbooks/httpd'
issues_url 'https://github.com/chef-cookbooks/httpd/issues'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
# supports 'smartos'
# supports 'omnios'
# supports 'suse'
