name 'httpd'
version '0.2.1'

supports 'amazon'
supports 'redhat'
supports 'centos'
supports 'scientific'
supports 'fedora'
supports 'debian'
supports 'ubuntu'
# supports 'smartos'
# supports 'omnios'
# supports 'suse'
